"""Sweep Pro license keys.

Licences are Ed25519-signed payloads, verified entirely offline — no backend, no
network call at runtime, works on a plane.

Key format: ``SWEEP-<base64url(payload)>.<base64url(signature)>``
where payload is compact JSON ``{"e": email, "o": order_id, "t": issued_at}``.

Why asymmetric
--------------
This module ships only the **public** key, which can verify but never sign. The
previous scheme used symmetric HMAC whose signing key derived from a literal in
this file, and exposed ``generate_key()`` in the same module — so anyone could
mint unlimited valid licences in one line. Signing now happens only in the
Cloudflare Worker that holds the private key.

Verification never raises. Callers gate privileged behaviour on ``check_pro()``,
so an exception path would be a bypass.

    from dreamcleanr.license import activate, check_pro
    activate("SWEEP-...")      # verifies, writes ~/.sweep_license (mode 600)
    is_pro = check_pro()       # runtime gate

Pro unlocks ``clean --apply`` and ``schedule``. Scanning, dry-run previews and
HTML reports stay free.
"""
from __future__ import annotations

import base64
import json
import time
from pathlib import Path

from ._ed25519 import verify as _ed_verify

# Ed25519 PUBLIC key — safe to ship, it can only verify.
# Generated by scripts/gen_license_keypair.py; the matching private key lives
# only in the Cloudflare secret SWEEP_LICENSE_PRIVATE_KEY.
PUBLIC_KEY = bytes.fromhex(
    "addff4a70e669520aae83be077efdcb785dd3b50f93f08191b226d0567056211"
)

_KEY_PREFIX = "SWEEP-"
_LICENSE_FILE = Path.home() / ".sweep_license"


def _b64d(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


# ── Verification ─────────────────────────────────────────────────────────────


def parse_key(key: str) -> dict | None:
    """Return the signed payload if ``key`` verifies, else None. Never raises."""
    try:
        if not key or not key.startswith(_KEY_PREFIX):
            return None
        payload_b64, sep, sig_b64 = key[len(_KEY_PREFIX):].partition(".")
        if not sep or not payload_b64 or not sig_b64:
            return None
        payload_raw = _b64d(payload_b64)
        if not _ed_verify(PUBLIC_KEY, _b64d(sig_b64), payload_raw):
            return None
        data = json.loads(payload_raw)
        if not isinstance(data, dict) or "e" not in data:
            return None
        return data
    except Exception:
        return None


# ── Activation (writes ~/.sweep_license) ─────────────────────────────────────


def activate(key: str) -> dict:
    """Verify and persist a licence.

    The purchase email comes from inside the signed payload, so the user no
    longer has to retype it (and cannot mistype it).

    Raises ValueError with a human-readable message if the key is invalid.
    """
    data = parse_key(key.strip())
    if data is None:
        raise ValueError(
            "That licence key is not valid.\n"
            "Copy it exactly as it appears in your receipt email.\n"
            "Need help? Email support@jonlynchfinancial.com"
        )
    record = {
        "key": key.strip(),
        "email": data["e"],
        "order": data.get("o"),
        "activated_at": int(time.time()),
        "tier": "pro",
    }
    _LICENSE_FILE.write_text(json.dumps(record, indent=2))
    _LICENSE_FILE.chmod(0o600)
    return record


# ── Runtime check ────────────────────────────────────────────────────────────


def check_pro() -> bool:
    """True only if a stored licence verifies right now. Never raises.

    Re-verifies the signature on every call rather than trusting the stored
    record, so hand-editing ~/.sweep_license grants nothing.
    """
    return get_license_info() is not None


def get_license_info() -> dict | None:
    """Return {email, order, activated_at} if a valid licence is installed."""
    try:
        if not _LICENSE_FILE.exists():
            return None
        record = json.loads(_LICENSE_FILE.read_text())
        data = parse_key(record.get("key", ""))
        if data is None:
            return None
        return {
            "email": data["e"],
            "order": data.get("o"),
            "activated_at": record.get("activated_at"),
        }
    except Exception:
        return None


def deactivate() -> bool:
    """Remove the licence file. Returns True if it existed."""
    if _LICENSE_FILE.exists():
        _LICENSE_FILE.unlink()
        return True
    return False
